### ISSUE TITLE
Question: Updated typings

### ISSUE THREAD

**Issue by JamesSkemp** [seibert-media/ajs-type#1]
I'm looking at working with AJS as part of a new project and this project appears to be the only project that has any TypeScript definitions.

Is there a newer version of these definitions somewhere?

If not, do you have any information on how you went about generating the definitions?

Thanks!

**Comment by j-frost** [comment]
This project is for work and I was out of the office last week, so sorry for answering only now. 

I'm not involved with Atlassian plugin development any longer, so I'll ask around what happened here. Last I remember I marked this as deprecated and unsupported because I stepped away from Confluence plugin dev and because at the time we didn't use TypeScript extensively. I know this has changed, and since there's no hint on the README about inactivity, I assume we still use it. Will get back to you once I know more :)

**Comment by j-frost** [comment]
Alright so I checked with our teams and this is the case: We currently use this package in most of our Atlassian server apps. Yes, they're sorta out of date, but nothing much changed. It was mostly new additions, and didn't get in the way. So that's why this repo wasn't updated much. I just created #2 to fix some inconveniences and once that's merged I'll push it to npm too. 

In the mean time, if you want to contribute to this project (either with convenience features or additional typings), feel free to open a PR. Ideally also mention for which version of AJS those changes are. Further info in the [README section Contributing](https://github.com/seibert-media/ajs-type#contributing). Since this repo has to account for versioning both external (AJS versions) and internal (patches on typings within a single AJS version), tagging and npm packaging is a little complex, so I'll continue to manage that for you. 

As for generating typings, unfortunately that's a bunch of manual effort. Also the script we used to generate the existing typings may not work any longer. Here's how you do it: You'll want to use the `generator-script.ts`. You can build it by running `npm run build`. This will generate JavaScript which you can copy into the `index.d.ts` and manually change typings until they're correct or you're satisfied that they fulfill your requirements. 

I suspect this being left relatively untouched for quite a while is partly due to this effort, and now with Atlassian having announced they're sunsetting their server applications, it's likely this repo will still not see a lot of love. If you're nonetheless interested in using ajs-type and run across further issues, do feel free to open further issues / PRs or contact me at jrost at seibert dash media dot com. Google Chat or simply e-mail.

**Comment by JamesSkemp** [comment]
Just realized I neglected to comment on this last week.

A belated thank you for the insights! :)
